import Head from "next/head";
import ContentContainer from "@/components/ContentContainer/ContentContainer";
import Hero from "@/components/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/g" />
      </Head>
      <div>
        <main style={{ backgroundColor: "#F8F8F8" }}>
          <Hero pageInfo={{
            title: "Welcome to My Portfolio",
            description: "This is a showcase of my work.",
            featuredImage: {
              src: "/jsabet1.jpg",
              alt: "A description of the image",
              width: 800,
              height: 600
            }
          }} />
          <section style={{ paddingTop: "16px" }}>
            <ContentContainer>
              <div style={{ display: "flex", flexDirection: "column", gap: "16px", justifyContent: "center", width: "100%", height: "500px", padding: "25px"}}>
                <h2>About Me</h2>
                <p>This is a brief description about me.</p>
              </div>
            </ContentContainer>
          </section>
        </main>
      </div>
    </>
  );
}
