import Head from "next/head";
import Hero from "@/components/Hero/Hero";
import Card from "@/components/Card/Card";
import PorfolioCard from "@/components/pages/portfolio/PortfolioCard/PorfolioCard";
import ResumeCard from "@/components/pages/resume/ResumeCard/ResumeCard";

export default function Home() {
  const jobDummyData = {
    companyName: "Testing Co.",
    jobTitle: "Web Developer in Test",
    startDate:  'Jan 1, 2020',
    endDate: null,
    description: "Yeah, but your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should. Yeah, but your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should. Yes, Yes, without the oops!",
    websiteURL: "https://henryscheinortho.com",
    responsibilities: "Checkmate... Life finds a way. This thing comes fully loaded. AM/FM radio, reclining bucket seats, and... power windows. Just my luck, no ice. Yeah, but your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should.",
    projects: [{
      name: "WebPunk",
      websiteURL: "https://webpunk.tech",
      technologies: ["Next.js", "React", "Framer Motion", "Strapi CMS"],
      description: "Checkmate... Life finds a way. This thing comes fully loaded. AM/FM radio, reclining bucket seats, and... power windows. Just my luck, no ice. Yeah, but your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should."
    }],
    featuredImage: {
      src: "https://cdn.prod.website-files.com/62ecf6509147fe25583ba07a/688bec760ef8c221a30e34f8_1.jpg",
      alt: "Protrending Website",
      width: "500px",
      height: "auto"
    },
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/g" />
      </Head>
      <div>
        <main style={{ backgroundColor: "#F8F8F8" }}>
          <Hero pageInfo={{
            title: "Welcome to My Portfolio",
            description: "This is a showcase of my work.",
            featuredImage: {
              src: "/jsabet1.jpg",
              alt: "A description of the image",
              width: "800px",
              height: "600px"
            }
          }} />
          <section style={{ paddingTop: "16px", maxWidth: "1200px", margin: "0 auto" }}>
            <Card>
              <ResumeCard job={jobDummyData} />
            </Card>
          </section>
        </main>
      </div>
    </>
  );
}
