import Head from "next/head";
import Markdown from "markdown-to-jsx";
//API Imports
import type { GetStaticProps, InferGetStaticPropsType } from 'next';
import { getAboutPage } from '@/lib/api';
import { AboutPageProps } from "@/types/interfaces";
//Component Imports
import Hero from "@/components/Hero/Hero";
import ContentContainer from "@/components/ContentContainer/ContentContainer";
import About from "@/components/pages/home/About/About";

export default function Home({ data }: InferGetStaticPropsType<typeof getStaticProps>) {

  return (
    <>
      <Head>
        <title>Sean Standen | About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/g" />
      </Head>
      <div>
        <main style={{ backgroundColor: "#F8F8F8", margin: "50px 0 100px" }}>
          <Hero pageInfo={{
            Title: "Welcome to My Portfolio",
            Description: "This is a showcase of my work.",
            featuredImage: {
              src: "/jsabet1.jpg",
              alt: "A description of the image",
              width: "800px",
              height: "600px"
            }
          }} />
          <section style={{ paddingTop: "16px", maxWidth: "1200px", margin: "0 auto" }}>
            <ContentContainer>
                <About data={data} />
            </ContentContainer>
          </section>
        </main>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps<AboutPageProps> = async (context) => {
      // Fetch your data here
      const fetchedData = await getAboutPage();
      return {
        props: {
          data: fetchedData
        },
      };
};
